# -*- coding: utf-8 -*-
"""Criando um sistema de recomendação por imagens digitais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaKcLQuyMf3Le33RfsPPjOLJCUEWcsAE
"""

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import os
from PIL import Image
import matplotlib.pyplot as plt

# 1. Dataset Loading and Preprocessing
dataset_path = "dataset/"  # Replace with your dataset path

if not os.path.exists(dataset_path):
    print("Please upload your dataset folder as 'dataset/'")
else:
    train_dataset = tf.keras.preprocessing.image_dataset_from_directory(
        dataset_path,
        labels="inferred",
        label_mode="categorical",
        seed=123,
        image_size=(224, 224),
        batch_size=32
    )

    class_names = train_dataset.class_names
    num_classes = len(class_names)

    # 2. Model Setup
    base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    model = Model(inputs=base_model.input, outputs=x)

    # 3. Feature Extraction
    def extract_features(dataset, model):
        features = []
        labels = []
        for images, label_batch in dataset:
            batch_features = model.predict(images)
            features.extend(batch_features)
            labels.extend(label_batch.numpy())
        return np.array(features), np.array(labels)

    features, labels = extract_features(train_dataset, model)

    # 4. Similarity Calculation and Recommendation
    def recommend_similar_images(query_image_path, features, labels, class_names, num_recommendations=5):
        img = image.load_img(query_image_path, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0)
        query_features = model.predict(img_array)

        similarities = cosine_similarity(query_features, features)[0]
        similar_indices = np.argsort(similarities)[::-1][1:num_recommendations+1] # Exclude the query image itself

        print("Recommendations:")
        plt.figure(figsize=(15, 5))
        plt.subplot(1, num_recommendations+1, 1)
        plt.imshow(img)
        plt.title("Query Image")
        plt.axis('off')

        for i, idx in enumerate(similar_indices):
            class_label = np.argmax(labels[idx])
            image_path = os.path.join(dataset_path, class_names[class_label], os.listdir(os.path.join(dataset_path, class_names[class_label]))[idx])
            recommended_img = Image.open(image_path)

            plt.subplot(1, num_recommendations+1, i+2)
            plt.imshow(recommended_img)
            plt.title(f"Similarity: {similarities[idx]:.2f}")
            plt.axis('off')

        plt.show()

    # 5. Example Usage (Replace with your query image path)
    query_image_path = "dataset/watches/watch1.jpg"  # Replace with a path to an image in your dataset
    if os.path.exists(query_image_path):
      recommend_similar_images(query_image_path, features, labels, class_names)
    else:
      print("Query image not found. Please upload a query image to your dataset directory.")